import { AlertTriangleIcon, ArrowLeft } from "lucide-react";
import React from "react";

const page = () => {
  return (
    <div className="antialiased min-h-screen p-4 sm:p-8 bg-green-50">
      <div className="max-w-4xl mx-auto bg-white shadow-2xl rounded-xl p-6 md:p-10  ">
        {/* Back Button */}
        <a
          href="/"
          className="inline-flex p-3 rounded-2xl items-center bg-green-600 text-white hover:text-green-400 transition duration-150 mb-8 font-medium sticky top-5"
        >
          <ArrowLeft className="w-5 h-5 mr-1" />
          Back to Mogger AI
        </a>

        {/* Header */}
        <header className="mb-10 border-b pb-4">
          <h2 className="text-3xl font-semibold text-green-600">
            Mogger AI (Demo Version)
          </h2>
          <h1 className="text-xl font-bold text-green-900 mb-2 tracking-tight">
            Terms of Service
          </h1>
          <p className="text-sm text-gray-500 mt-2">
            Last Updated: November 8, 2025
          </p>
        </header>

        {/* Content Sections */}
        <div className="space-y-8 text-gray-700 leading-relaxed">
          {/* 1. Acceptance of Terms */}
          <section>
            <h3 className="text-2xl font-bold text-green-700 mb-3">
              1. Acceptance of Terms
            </h3>
            <p>
              Welcome to <strong>Mogger AI</strong> ("the App," "the Service,"
              "we," "us," or "our"). The Service is an AI-powered educational
              application designed to create study materials and tests (such as
              "mogs") to help users prepare for exams.
            </p>
            <p className="mt-2">
              By accessing or using the Service, you agree to be bound by these
              Terms of Service ("Terms"). If you disagree with any part of the
              terms, you may not access the Service.
            </p>
          </section>

          {/* 2. DEMO Product Disclaimer (Crucial - Yellow Warning Box) */}
          <section className="p-6 bg-green-50 border border-green-300 rounded-lg shadow-md">
            <h3 className="text-2xl font-bold text-green-800 mb-4 flex items-center">
              <AlertTriangleIcon className="w-7 h-7 mr-3 text-green-600" />
              2. DEMO Product Disclaimer
            </h3>
            <p className="text-green-700 font-bold">
              <strong>
                Mogger AI is currently a prototype and a non-commercial
                demonstration product. It is NOT a full-fledged release.
              </strong>
            </p>
            <ul className="list-disc list-inside ml-4 mt-3 text-green-800 space-y-1">
              <li>
                The Service is provided on an "AS IS" and "AS AVAILABLE" basis.
                We offer no guarantees of uptime, stability, accuracy, or data
                retention.
              </li>
              <li>
                We reserve the right to suspend, terminate, or modify the
                Service at any time without prior notice.
              </li>
              <li>
                Any reliance you place on the content generated by this demo
                application is strictly at your own risk.
              </li>
            </ul>
          </section>

          {/* 3. Third-Party API Usage (Gemini/Google) */}
          <section>
            <h3 className="text-2xl font-bold text-green-700 mb-3">
              3. Third-Party API Usage (Gemini/Google)
            </h3>
            <p>
              The core functionality of the Service (generating tests, study
              materials, and other content) relies on the Google Gemini API,
              which is a proprietary service provided by Google.
            </p>
            <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
              <li>
                <strong>Compliance:</strong> By using the AI features of the
                App, you acknowledge and agree that your use is also governed by
                and conditioned upon your compliance with the relevant Google
                Terms of Service and policies, including those governing the use
                of the Gemini API.
              </li>
              <li>
                <strong>Content Accuracy:</strong> You understand that content
                generated by the AI is based on machine learning models and may
                not be accurate, complete, or reflective of factual information.
              </li>
            </ul>
          </section>

          {/* 4. Intellectual Property and User Content */}
          <section>
            <h3 className="text-2xl font-bold text-green-700 mb-3">
              4. Intellectual Property and User Content
            </h3>
            <p>
              The Service and its original content, features, and functionality
              (excluding content provided by the Gemini API or users) are and
              will remain the exclusive property of Mogger AI and its licensors.
            </p>
            <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
              <li>
                <strong>Prohibited Uses:</strong> You agree not to misuse the
                Service, including but not limited to generating content that is
                illegal, defamatory, harassing, or violates any third-party
                intellectual property rights.
              </li>
              <li>
                <strong>License to User Content:</strong> By submitting content
                (e.g., test prompts) to the App, you grant us a worldwide,
                non-exclusive, royalty-free license to use, reproduce, modify,
                and display that content for the purpose of operating and
                improving the Service.
              </li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default page;
